name: drem-dev
channels:
  - conda-forge
dependencies:
  # Most up-to-date compatible version according to `poetry update python`
  - python=3.8.3

  # Geospatial analysis
  - geopandas
  - descartes
  - mapclassify
  - rtree
  - pygeos

  # Prefect flow visualization
  - graphviz
