# -*- coding: utf-8 -*-
# flake8: noqa

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

setup(
    long_description="README.md",
    name="drem",
    version="0.3.1",
    description="https://www.codema.ie/projects/local-projects/dublin-region-energy-master-plan",
    python_requires="==3.*,>=3.8.0",
    project_urls={"repository": "https://github.com/codema-dev/drem"},
    author="Rowan Molony",
    author_email="rowan.molony@codema.ie",
    license="MIT",
    packages=["drem"],
    package_dir={"": "src"},
    install_requires=[
        "bs4==0.*,>=0.0.1",
        "dask[dataframe]==2.*,>=2.26.0",
        "descartes==1.*,>=1.1.0",
        "geopandas==0.*,>=0.8.1",
        "html5lib==1.*,>=1.1.0",
        "icontract==2.*,>=2.3.4",
        "loguru==0.*,>=0.5.3",
        "lxml==4.*,>=4.5.2",
        "matplotlib==3.*,>=3.3.0",
        "openpyxl==3.*,>=3.0.4",
        "pandas==1.*,>=1.1.0",
        "prefect==0.*,>=0.13.0",
        "pyarrow==1.*,>=1.0.0",
        "pygeos==0.*,>=0.7.1",
        "requests==2.*,>=2.24.0",
        "seaborn==0.*,>=0.11.0",
        "tqdm==4.*,>=4.48.2",
        "unidecode==1.*,>=1.1.1",
        "validate-email==1.*,>=1.3.0",
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0",
            "ipdb==0.*,>=0.13.3",
            "ipython==7.*,>=7.17.0",
            "mypy==0.*,>=0.782.0",
            "pandas-vet==0.*,>=0.2.2",
            "pdbpp==0.*,>=0.10.2",
            "poetry2conda==0.*,>=0.3.0",
            "pre-commit==2.*,>=2.6.0",
            "pygments==2.*,>=2.7.1",
            "pyicontract-lint==2.*,>=2.0.0",
            "pytest==6.*,>=6.0.1",
            "pytest-cov==2.*,>=2.10.0",
            "pytest-xdist==1.*,>=1.34.0",
            "responses==0.*,>=0.12.0",
            "seed-isort-config==2.*,>=2.2.0",
            "wemake-python-styleguide==0.*,>=0.14.1",
        ],
    },
)
