{% set name = "drem" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drem-{{ version }}.tar.gz
  sha256: 5f3b798cc95d7b1346cc9209ef31ad3d15e1048c70e0b9eef6b75e13489fcffe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python>=3.8,<4.0
    - pandas>=1.1.0,<2.0.0
    - requests>=2.24.0,<3.0.0
    - tqdm>=4.48.2,<5.0.0
    - geopandas>=0.8.1,<0.9.0
    - openpyxl>=3.0.4,<4.0.0
    - matplotlib>=3.3.0,<4.0.0
    - unidecode>=1.1.1,<2.0.0
    - descartes>=1.1.0,<2.0.0
    - dask>=2.26.0,<3.0.0
    - seaborn>=0.11.0,<0.12.0
    - lxml>=4.5.2,<5.0.0
    - html5lib>=1.1,<2.0
    - pip
    - pip:
      - prefect>=0.13.0,<0.14.0
      - icontract>=2.3.4,<3.0.0
      - pyarrow>=1.0.0,<2.0.0
      - pygeos>=0.7.1,<0.8.0
      - validate_email>=1.3,<2.0
      - graphviz>=0.14.1,<0.15.0
      - loguru>=0.5.3,<0.6.0
      - bs4>=0.0.1,<0.0.2

test:
  imports:
    - drem
    - drem.download
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/codema-dev/drem
  summary: https://www.codema.ie/projects/local-projects/dublin-region-energy-master-plan
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rdmolony
