all:
	runipy "1_Apply_BER_Archetypes_to_Census_2011.ipynb"
	runipy "2_Calculate_total_demand_for_each_archetype.ipynb"
	runipy "3_Aggregate_Archetype_demand_to_SA.ipynb"
	runipy "4_Store_Archetype_models.ipynb"
