all:
	runipy "1_Read_in_Dublin_data.ipynb"
	runipy "2_Calculate_Postcode_averages.ipynb"
	runipy "3_Calculate_overall_Dublin_averages.ipynb"
	runipy "4_Replace_null_values_with_overall_Dublin_average.ipynb"
